# generated by datamodel-codegen:
#   filename:  recent_trades_list.json
#   timestamp: 2023-07-05T21:28:11+00:00

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Field


class Model(BaseModel):
    __root__: List[Dict[str, Any]] = Field(..., unique_items=False)
